# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_auditing_data import ResponseAuditingData  # noqa: F401,E501
from swagger_server import util


class AuditingData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, responses: List[ResponseAuditingData]=None, task_id: int=None, location_id: int=None, responsible: str=None, user: str=None):  # noqa: E501
        """AuditingData - a model defined in Swagger

        :param responses: The responses of this AuditingData.  # noqa: E501
        :type responses: List[ResponseAuditingData]
        :param task_id: The task_id of this AuditingData.  # noqa: E501
        :type task_id: int
        :param location_id: The location_id of this AuditingData.  # noqa: E501
        :type location_id: int
        :param responsible: The responsible of this AuditingData.  # noqa: E501
        :type responsible: str
        :param user: The user of this AuditingData.  # noqa: E501
        :type user: str
        """
        self.swagger_types = {
            'responses': List[ResponseAuditingData],
            'task_id': int,
            'location_id': int,
            'responsible': str,
            'user': str
        }

        self.attribute_map = {
            'responses': 'responses',
            'task_id': 'task_id',
            'location_id': 'location_id',
            'responsible': 'responsible',
            'user': 'user'
        }
        self._responses = responses
        self._task_id = task_id
        self._location_id = location_id
        self._responsible = responsible
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'AuditingData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuditingData of this AuditingData.  # noqa: E501
        :rtype: AuditingData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def responses(self) -> List[ResponseAuditingData]:
        """Gets the responses of this AuditingData.


        :return: The responses of this AuditingData.
        :rtype: List[ResponseAuditingData]
        """
        return self._responses

    @responses.setter
    def responses(self, responses: List[ResponseAuditingData]):
        """Sets the responses of this AuditingData.


        :param responses: The responses of this AuditingData.
        :type responses: List[ResponseAuditingData]
        """

        self._responses = responses

    @property
    def task_id(self) -> int:
        """Gets the task_id of this AuditingData.


        :return: The task_id of this AuditingData.
        :rtype: int
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id: int):
        """Sets the task_id of this AuditingData.


        :param task_id: The task_id of this AuditingData.
        :type task_id: int
        """

        self._task_id = task_id

    @property
    def location_id(self) -> int:
        """Gets the location_id of this AuditingData.


        :return: The location_id of this AuditingData.
        :rtype: int
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id: int):
        """Sets the location_id of this AuditingData.


        :param location_id: The location_id of this AuditingData.
        :type location_id: int
        """

        self._location_id = location_id

    @property
    def responsible(self) -> str:
        """Gets the responsible of this AuditingData.


        :return: The responsible of this AuditingData.
        :rtype: str
        """
        return self._responsible

    @responsible.setter
    def responsible(self, responsible: str):
        """Sets the responsible of this AuditingData.


        :param responsible: The responsible of this AuditingData.
        :type responsible: str
        """

        self._responsible = responsible

    @property
    def user(self) -> str:
        """Gets the user of this AuditingData.


        :return: The user of this AuditingData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this AuditingData.


        :param user: The user of this AuditingData.
        :type user: str
        """

        self._user = user
