# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DriverCompanionData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_driver_companion: int=None, name: str=None):  # noqa: E501
        """DriverCompanionData - a model defined in Swagger

        :param id_driver_companion: The id_driver_companion of this DriverCompanionData.  # noqa: E501
        :type id_driver_companion: int
        :param name: The name of this DriverCompanionData.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'id_driver_companion': int,
            'name': str
        }

        self.attribute_map = {
            'id_driver_companion': 'id_driver_companion',
            'name': 'name'
        }
        self._id_driver_companion = id_driver_companion
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'DriverCompanionData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DriverCompanionData of this DriverCompanionData.  # noqa: E501
        :rtype: DriverCompanionData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_driver_companion(self) -> int:
        """Gets the id_driver_companion of this DriverCompanionData.


        :return: The id_driver_companion of this DriverCompanionData.
        :rtype: int
        """
        return self._id_driver_companion

    @id_driver_companion.setter
    def id_driver_companion(self, id_driver_companion: int):
        """Sets the id_driver_companion of this DriverCompanionData.


        :param id_driver_companion: The id_driver_companion of this DriverCompanionData.
        :type id_driver_companion: int
        """

        self._id_driver_companion = id_driver_companion

    @property
    def name(self) -> str:
        """Gets the name of this DriverCompanionData.


        :return: The name of this DriverCompanionData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DriverCompanionData.


        :param name: The name of this DriverCompanionData.
        :type name: str
        """

        self._name = name
