# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.driver_companion_data import DriverCompanionData  # noqa: F401,E501
from swagger_server import util


class DriverCompanion(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[DriverCompanionData]=None):  # noqa: E501
        """DriverCompanion - a model defined in Swagger

        :param data: The data of this DriverCompanion.  # noqa: E501
        :type data: List[DriverCompanionData]
        """
        self.swagger_types = {
            'data': List[DriverCompanionData]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'DriverCompanion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DriverCompanion of this DriverCompanion.  # noqa: E501
        :rtype: DriverCompanion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[DriverCompanionData]:
        """Gets the data of this DriverCompanion.


        :return: The data of this DriverCompanion.
        :rtype: List[DriverCompanionData]
        """
        return self._data

    @data.setter
    def data(self, data: List[DriverCompanionData]):
        """Sets the data of this DriverCompanion.


        :param data: The data of this DriverCompanion.
        :type data: List[DriverCompanionData]
        """

        self._data = data
