# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FindingAuditingData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, description: str=None, criticality: str=None, responsible: str=None, commitment: str=None, images: List[str]=None):  # noqa: E501
        """FindingAuditingData - a model defined in Swagger

        :param description: The description of this FindingAuditingData.  # noqa: E501
        :type description: str
        :param criticality: The criticality of this FindingAuditingData.  # noqa: E501
        :type criticality: str
        :param responsible: The responsible of this FindingAuditingData.  # noqa: E501
        :type responsible: str
        :param commitment: The commitment of this FindingAuditingData.  # noqa: E501
        :type commitment: str
        :param images: The images of this FindingAuditingData.  # noqa: E501
        :type images: List[str]
        """
        self.swagger_types = {
            'description': str,
            'criticality': str,
            'responsible': str,
            'commitment': str,
            'images': List[str]
        }

        self.attribute_map = {
            'description': 'description',
            'criticality': 'criticality',
            'responsible': 'responsible',
            'commitment': 'commitment',
            'images': 'images'
        }
        self._description = description
        self._criticality = criticality
        self._responsible = responsible
        self._commitment = commitment
        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'FindingAuditingData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindingAuditingData of this FindingAuditingData.  # noqa: E501
        :rtype: FindingAuditingData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this FindingAuditingData.


        :return: The description of this FindingAuditingData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this FindingAuditingData.


        :param description: The description of this FindingAuditingData.
        :type description: str
        """

        self._description = description

    @property
    def criticality(self) -> str:
        """Gets the criticality of this FindingAuditingData.


        :return: The criticality of this FindingAuditingData.
        :rtype: str
        """
        return self._criticality

    @criticality.setter
    def criticality(self, criticality: str):
        """Sets the criticality of this FindingAuditingData.


        :param criticality: The criticality of this FindingAuditingData.
        :type criticality: str
        """

        self._criticality = criticality

    @property
    def responsible(self) -> str:
        """Gets the responsible of this FindingAuditingData.


        :return: The responsible of this FindingAuditingData.
        :rtype: str
        """
        return self._responsible

    @responsible.setter
    def responsible(self, responsible: str):
        """Sets the responsible of this FindingAuditingData.


        :param responsible: The responsible of this FindingAuditingData.
        :type responsible: str
        """

        self._responsible = responsible

    @property
    def commitment(self) -> str:
        """Gets the commitment of this FindingAuditingData.


        :return: The commitment of this FindingAuditingData.
        :rtype: str
        """
        return self._commitment

    @commitment.setter
    def commitment(self, commitment: str):
        """Sets the commitment of this FindingAuditingData.


        :param commitment: The commitment of this FindingAuditingData.
        :type commitment: str
        """

        self._commitment = commitment

    @property
    def images(self) -> List[str]:
        """Gets the images of this FindingAuditingData.


        :return: The images of this FindingAuditingData.
        :rtype: List[str]
        """
        return self._images

    @images.setter
    def images(self, images: List[str]):
        """Sets the images of this FindingAuditingData.


        :param images: The images of this FindingAuditingData.
        :type images: List[str]
        """

        self._images = images
