# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProjectsData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_project: int=None, name: str=None):  # noqa: E501
        """ProjectsData - a model defined in Swagger

        :param id_project: The id_project of this ProjectsData.  # noqa: E501
        :type id_project: int
        :param name: The name of this ProjectsData.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'id_project': int,
            'name': str
        }

        self.attribute_map = {
            'id_project': 'id_project',
            'name': 'name'
        }
        self._id_project = id_project
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProjectsData of this ProjectsData.  # noqa: E501
        :rtype: ProjectsData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_project(self) -> int:
        """Gets the id_project of this ProjectsData.


        :return: The id_project of this ProjectsData.
        :rtype: int
        """
        return self._id_project

    @id_project.setter
    def id_project(self, id_project: int):
        """Sets the id_project of this ProjectsData.


        :param id_project: The id_project of this ProjectsData.
        :type id_project: int
        """

        self._id_project = id_project

    @property
    def name(self) -> str:
        """Gets the name of this ProjectsData.


        :return: The name of this ProjectsData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProjectsData.


        :param name: The name of this ProjectsData.
        :type name: str
        """

        self._name = name
