# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.projects_data import ProjectsData  # noqa: F401,E501
from swagger_server import util


class Project(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[ProjectsData]=None):  # noqa: E501
        """Project - a model defined in Swagger

        :param data: The data of this Project.  # noqa: E501
        :type data: List[ProjectsData]
        """
        self.swagger_types = {
            'data': List[ProjectsData]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Project':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Project of this Project.  # noqa: E501
        :rtype: Project
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[ProjectsData]:
        """Gets the data of this Project.


        :return: The data of this Project.
        :rtype: List[ProjectsData]
        """
        return self._data

    @data.setter
    def data(self, data: List[ProjectsData]):
        """Sets the data of this Project.


        :param data: The data of this Project.
        :type data: List[ProjectsData]
        """

        self._data = data
