# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReasonsData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_reason: int=None, reason: str=None):  # noqa: E501
        """ReasonsData - a model defined in Swagger

        :param id_reason: The id_reason of this ReasonsData.  # noqa: E501
        :type id_reason: int
        :param reason: The reason of this ReasonsData.  # noqa: E501
        :type reason: str
        """
        self.swagger_types = {
            'id_reason': int,
            'reason': str
        }

        self.attribute_map = {
            'id_reason': 'id_reason',
            'reason': 'reason'
        }
        self._id_reason = id_reason
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'ReasonsData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReasonsData of this ReasonsData.  # noqa: E501
        :rtype: ReasonsData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_reason(self) -> int:
        """Gets the id_reason of this ReasonsData.


        :return: The id_reason of this ReasonsData.
        :rtype: int
        """
        return self._id_reason

    @id_reason.setter
    def id_reason(self, id_reason: int):
        """Sets the id_reason of this ReasonsData.


        :param id_reason: The id_reason of this ReasonsData.
        :type id_reason: int
        """

        self._id_reason = id_reason

    @property
    def reason(self) -> str:
        """Gets the reason of this ReasonsData.


        :return: The reason of this ReasonsData.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this ReasonsData.


        :param reason: The reason of this ReasonsData.
        :type reason: str
        """

        self._reason = reason
