# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reasons_data import ReasonsData  # noqa: F401,E501
from swagger_server import util


class Reasons(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[ReasonsData]=None):  # noqa: E501
        """Reasons - a model defined in Swagger

        :param data: The data of this Reasons.  # noqa: E501
        :type data: List[ReasonsData]
        """
        self.swagger_types = {
            'data': List[ReasonsData]
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Reasons':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reasons of this Reasons.  # noqa: E501
        :rtype: Reasons
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[ReasonsData]:
        """Gets the data of this Reasons.


        :return: The data of this Reasons.
        :rtype: List[ReasonsData]
        """
        return self._data

    @data.setter
    def data(self, data: List[ReasonsData]):
        """Sets the data of this Reasons.


        :param data: The data of this Reasons.
        :type data: List[ReasonsData]
        """

        self._data = data
