# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.technical_put_data import TechnicalPutData  # noqa: F401,E501
from swagger_server import util


class RequestPutTechnicalControl(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, technical_data: TechnicalPutData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestPutTechnicalControl - a model defined in Swagger

        :param technical_data: The technical_data of this RequestPutTechnicalControl.  # noqa: E501
        :type technical_data: TechnicalPutData
        :param channel: The channel of this RequestPutTechnicalControl.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestPutTechnicalControl.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'technical_data': TechnicalPutData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'technical_data': 'technical_data',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._technical_data = technical_data
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPutTechnicalControl':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPutTechnicalControl of this RequestPutTechnicalControl.  # noqa: E501
        :rtype: RequestPutTechnicalControl
        """
        return util.deserialize_model(dikt, cls)

    @property
    def technical_data(self) -> TechnicalPutData:
        """Gets the technical_data of this RequestPutTechnicalControl.


        :return: The technical_data of this RequestPutTechnicalControl.
        :rtype: TechnicalPutData
        """
        return self._technical_data

    @technical_data.setter
    def technical_data(self, technical_data: TechnicalPutData):
        """Sets the technical_data of this RequestPutTechnicalControl.


        :param technical_data: The technical_data of this RequestPutTechnicalControl.
        :type technical_data: TechnicalPutData
        """

        self._technical_data = technical_data

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestPutTechnicalControl.


        :return: The channel of this RequestPutTechnicalControl.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestPutTechnicalControl.


        :param channel: The channel of this RequestPutTechnicalControl.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestPutTechnicalControl.


        :return: The external_transaction_id of this RequestPutTechnicalControl.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestPutTechnicalControl.


        :param external_transaction_id: The external_transaction_id of this RequestPutTechnicalControl.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
