# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.auditing_data import AuditingData  # noqa: F401,E501
from swagger_server import util


class RequestPostAuditing(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: AuditingData=None, auditor_img: str=None, responsible_img: str=None, client_img: str=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestPostAuditing - a model defined in Swagger

        :param data: The data of this RequestPostAuditing.  # noqa: E501
        :type data: AuditingData
        :param auditor_img: The auditor_img of this RequestPostAuditing.  # noqa: E501
        :type auditor_img: str
        :param responsible_img: The responsible_img of this RequestPostAuditing.  # noqa: E501
        :type responsible_img: str
        :param client_img: The client_img of this RequestPostAuditing.  # noqa: E501
        :type client_img: str
        :param channel: The channel of this RequestPostAuditing.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestPostAuditing.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'data': AuditingData,
            'auditor_img': str,
            'responsible_img': str,
            'client_img': str,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'data': 'data',
            'auditor_img': 'auditor_img',
            'responsible_img': 'responsible_img',
            'client_img': 'client_img',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._data = data
        self._auditor_img = auditor_img
        self._responsible_img = responsible_img
        self._client_img = client_img
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPostAuditing':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPostAuditing of this RequestPostAuditing.  # noqa: E501
        :rtype: RequestPostAuditing
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> AuditingData:
        """Gets the data of this RequestPostAuditing.


        :return: The data of this RequestPostAuditing.
        :rtype: AuditingData
        """
        return self._data

    @data.setter
    def data(self, data: AuditingData):
        """Sets the data of this RequestPostAuditing.


        :param data: The data of this RequestPostAuditing.
        :type data: AuditingData
        """

        self._data = data

    @property
    def auditor_img(self) -> str:
        """Gets the auditor_img of this RequestPostAuditing.


        :return: The auditor_img of this RequestPostAuditing.
        :rtype: str
        """
        return self._auditor_img

    @auditor_img.setter
    def auditor_img(self, auditor_img: str):
        """Sets the auditor_img of this RequestPostAuditing.


        :param auditor_img: The auditor_img of this RequestPostAuditing.
        :type auditor_img: str
        """

        self._auditor_img = auditor_img

    @property
    def responsible_img(self) -> str:
        """Gets the responsible_img of this RequestPostAuditing.


        :return: The responsible_img of this RequestPostAuditing.
        :rtype: str
        """
        return self._responsible_img

    @responsible_img.setter
    def responsible_img(self, responsible_img: str):
        """Sets the responsible_img of this RequestPostAuditing.


        :param responsible_img: The responsible_img of this RequestPostAuditing.
        :type responsible_img: str
        """

        self._responsible_img = responsible_img

    @property
    def client_img(self) -> str:
        """Gets the client_img of this RequestPostAuditing.


        :return: The client_img of this RequestPostAuditing.
        :rtype: str
        """
        return self._client_img

    @client_img.setter
    def client_img(self, client_img: str):
        """Sets the client_img of this RequestPostAuditing.


        :param client_img: The client_img of this RequestPostAuditing.
        :type client_img: str
        """

        self._client_img = client_img

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestPostAuditing.


        :return: The channel of this RequestPostAuditing.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestPostAuditing.


        :param channel: The channel of this RequestPostAuditing.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestPostAuditing.


        :return: The external_transaction_id of this RequestPostAuditing.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestPostAuditing.


        :param external_transaction_id: The external_transaction_id of this RequestPostAuditing.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
