# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseAuditingData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, item_id: int=None, response: str=None, observation: str=None):  # noqa: E501
        """ResponseAuditingData - a model defined in Swagger

        :param item_id: The item_id of this ResponseAuditingData.  # noqa: E501
        :type item_id: int
        :param response: The response of this ResponseAuditingData.  # noqa: E501
        :type response: str
        :param observation: The observation of this ResponseAuditingData.  # noqa: E501
        :type observation: str
        """
        self.swagger_types = {
            'item_id': int,
            'response': str,
            'observation': str
        }

        self.attribute_map = {
            'item_id': 'item_id',
            'response': 'response',
            'observation': 'observation'
        }
        self._item_id = item_id
        self._response = response
        self._observation = observation

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseAuditingData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseAuditingData of this ResponseAuditingData.  # noqa: E501
        :rtype: ResponseAuditingData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_id(self) -> int:
        """Gets the item_id of this ResponseAuditingData.


        :return: The item_id of this ResponseAuditingData.
        :rtype: int
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id: int):
        """Sets the item_id of this ResponseAuditingData.


        :param item_id: The item_id of this ResponseAuditingData.
        :type item_id: int
        """

        self._item_id = item_id

    @property
    def response(self) -> str:
        """Gets the response of this ResponseAuditingData.


        :return: The response of this ResponseAuditingData.
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response: str):
        """Sets the response of this ResponseAuditingData.


        :param response: The response of this ResponseAuditingData.
        :type response: str
        """

        self._response = response

    @property
    def observation(self) -> str:
        """Gets the observation of this ResponseAuditingData.


        :return: The observation of this ResponseAuditingData.
        :rtype: str
        """
        return self._observation

    @observation.setter
    def observation(self, observation: str):
        """Sets the observation of this ResponseAuditingData.


        :param observation: The observation of this ResponseAuditingData.
        :type observation: str
        """

        self._observation = observation
