# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TaskData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, code: str=None, user: str=None):  # noqa: E501
        """TaskData - a model defined in Swagger

        :param name: The name of this TaskData.  # noqa: E501
        :type name: str
        :param description: The description of this TaskData.  # noqa: E501
        :type description: str
        :param code: The code of this TaskData.  # noqa: E501
        :type code: str
        :param user: The user of this TaskData.  # noqa: E501
        :type user: str
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'code': str,
            'user': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'code': 'code',
            'user': 'user'
        }
        self._name = name
        self._description = description
        self._code = code
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'TaskData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaskData of this TaskData.  # noqa: E501
        :rtype: TaskData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this TaskData.


        :return: The name of this TaskData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TaskData.


        :param name: The name of this TaskData.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this TaskData.


        :return: The description of this TaskData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TaskData.


        :param description: The description of this TaskData.
        :type description: str
        """

        self._description = description

    @property
    def code(self) -> str:
        """Gets the code of this TaskData.


        :return: The code of this TaskData.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this TaskData.


        :param code: The code of this TaskData.
        :type code: str
        """

        self._code = code

    @property
    def user(self) -> str:
        """Gets the user of this TaskData.


        :return: The user of this TaskData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this TaskData.


        :param user: The user of this TaskData.
        :type user: str
        """

        self._user = user
