# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TaskData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, location_id: int=None, name: str=None, description: str=None, responsible: str=None, inspection_id: int=None, start_date: datetime=None, end_date: datetime=None, assigned_technicians: List[str]=None, is_support: bool=None, user: str=None):  # noqa: E501
        """TaskData - a model defined in Swagger

        :param location_id: The location_id of this TaskData.  # noqa: E501
        :type location_id: int
        :param name: The name of this TaskData.  # noqa: E501
        :type name: str
        :param description: The description of this TaskData.  # noqa: E501
        :type description: str
        :param responsible: The responsible of this TaskData.  # noqa: E501
        :type responsible: str
        :param inspection_id: The inspection_id of this TaskData.  # noqa: E501
        :type inspection_id: int
        :param start_date: The start_date of this TaskData.  # noqa: E501
        :type start_date: datetime
        :param end_date: The end_date of this TaskData.  # noqa: E501
        :type end_date: datetime
        :param assigned_technicians: The assigned_technicians of this TaskData.  # noqa: E501
        :type assigned_technicians: List[str]
        :param is_support: The is_support of this TaskData.  # noqa: E501
        :type is_support: bool
        :param user: The user of this TaskData.  # noqa: E501
        :type user: str
        """
        self.swagger_types = {
            'location_id': int,
            'name': str,
            'description': str,
            'responsible': str,
            'inspection_id': int,
            'start_date': datetime,
            'end_date': datetime,
            'assigned_technicians': List[str],
            'is_support': bool,
            'user': str
        }

        self.attribute_map = {
            'location_id': 'location_id',
            'name': 'name',
            'description': 'description',
            'responsible': 'responsible',
            'inspection_id': 'inspection_id',
            'start_date': 'start_date',
            'end_date': 'end_date',
            'assigned_technicians': 'assigned_technicians',
            'is_support': 'is_support',
            'user': 'user'
        }
        self._location_id = location_id
        self._name = name
        self._description = description
        self._responsible = responsible
        self._inspection_id = inspection_id
        self._start_date = start_date
        self._end_date = end_date
        self._assigned_technicians = assigned_technicians
        self._is_support = is_support
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'TaskData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaskData of this TaskData.  # noqa: E501
        :rtype: TaskData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location_id(self) -> int:
        """Gets the location_id of this TaskData.


        :return: The location_id of this TaskData.
        :rtype: int
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id: int):
        """Sets the location_id of this TaskData.


        :param location_id: The location_id of this TaskData.
        :type location_id: int
        """

        self._location_id = location_id

    @property
    def name(self) -> str:
        """Gets the name of this TaskData.


        :return: The name of this TaskData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TaskData.


        :param name: The name of this TaskData.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this TaskData.


        :return: The description of this TaskData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TaskData.


        :param description: The description of this TaskData.
        :type description: str
        """

        self._description = description

    @property
    def responsible(self) -> str:
        """Gets the responsible of this TaskData.


        :return: The responsible of this TaskData.
        :rtype: str
        """
        return self._responsible

    @responsible.setter
    def responsible(self, responsible: str):
        """Sets the responsible of this TaskData.


        :param responsible: The responsible of this TaskData.
        :type responsible: str
        """

        self._responsible = responsible

    @property
    def inspection_id(self) -> int:
        """Gets the inspection_id of this TaskData.


        :return: The inspection_id of this TaskData.
        :rtype: int
        """
        return self._inspection_id

    @inspection_id.setter
    def inspection_id(self, inspection_id: int):
        """Sets the inspection_id of this TaskData.


        :param inspection_id: The inspection_id of this TaskData.
        :type inspection_id: int
        """

        self._inspection_id = inspection_id

    @property
    def start_date(self) -> datetime:
        """Gets the start_date of this TaskData.


        :return: The start_date of this TaskData.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: datetime):
        """Sets the start_date of this TaskData.


        :param start_date: The start_date of this TaskData.
        :type start_date: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self) -> datetime:
        """Gets the end_date of this TaskData.


        :return: The end_date of this TaskData.
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: datetime):
        """Sets the end_date of this TaskData.


        :param end_date: The end_date of this TaskData.
        :type end_date: datetime
        """

        self._end_date = end_date

    @property
    def assigned_technicians(self) -> List[str]:
        """Gets the assigned_technicians of this TaskData.


        :return: The assigned_technicians of this TaskData.
        :rtype: List[str]
        """
        return self._assigned_technicians

    @assigned_technicians.setter
    def assigned_technicians(self, assigned_technicians: List[str]):
        """Sets the assigned_technicians of this TaskData.


        :param assigned_technicians: The assigned_technicians of this TaskData.
        :type assigned_technicians: List[str]
        """

        self._assigned_technicians = assigned_technicians

    @property
    def is_support(self) -> bool:
        """Gets the is_support of this TaskData.


        :return: The is_support of this TaskData.
        :rtype: bool
        """
        return self._is_support

    @is_support.setter
    def is_support(self, is_support: bool):
        """Sets the is_support of this TaskData.


        :param is_support: The is_support of this TaskData.
        :type is_support: bool
        """

        self._is_support = is_support

    @property
    def user(self) -> str:
        """Gets the user of this TaskData.


        :return: The user of this TaskData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this TaskData.


        :param user: The user of this TaskData.
        :type user: str
        """

        self._user = user
