# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TechnicalData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, created_at: str=None, reasons: List[int]=None, project: List[int]=None, id_truck_license: int=None, id_driver: int=None, initial_gasoline_id: int=None, final_gasoline_id: int=None, initial_km: str=None, final_km: str=None, driver_companion: List[int]=None, destiny: str=None, exit_point: str=None, observations: str=None, created_by: str=None, initial_images: List[str]=None, final_images: List[str]=None):  # noqa: E501
        """TechnicalData - a model defined in Swagger

        :param created_at: The created_at of this TechnicalData.  # noqa: E501
        :type created_at: str
        :param reasons: The reasons of this TechnicalData.  # noqa: E501
        :type reasons: List[int]
        :param project: The project of this TechnicalData.  # noqa: E501
        :type project: List[int]
        :param id_truck_license: The id_truck_license of this TechnicalData.  # noqa: E501
        :type id_truck_license: int
        :param id_driver: The id_driver of this TechnicalData.  # noqa: E501
        :type id_driver: int
        :param initial_gasoline_id: The initial_gasoline_id of this TechnicalData.  # noqa: E501
        :type initial_gasoline_id: int
        :param final_gasoline_id: The final_gasoline_id of this TechnicalData.  # noqa: E501
        :type final_gasoline_id: int
        :param initial_km: The initial_km of this TechnicalData.  # noqa: E501
        :type initial_km: str
        :param final_km: The final_km of this TechnicalData.  # noqa: E501
        :type final_km: str
        :param driver_companion: The driver_companion of this TechnicalData.  # noqa: E501
        :type driver_companion: List[int]
        :param destiny: The destiny of this TechnicalData.  # noqa: E501
        :type destiny: str
        :param exit_point: The exit_point of this TechnicalData.  # noqa: E501
        :type exit_point: str
        :param observations: The observations of this TechnicalData.  # noqa: E501
        :type observations: str
        :param created_by: The created_by of this TechnicalData.  # noqa: E501
        :type created_by: str
        :param initial_images: The initial_images of this TechnicalData.  # noqa: E501
        :type initial_images: List[str]
        :param final_images: The final_images of this TechnicalData.  # noqa: E501
        :type final_images: List[str]
        """
        self.swagger_types = {
            'created_at': str,
            'reasons': List[int],
            'project': List[int],
            'id_truck_license': int,
            'id_driver': int,
            'initial_gasoline_id': int,
            'final_gasoline_id': int,
            'initial_km': str,
            'final_km': str,
            'driver_companion': List[int],
            'destiny': str,
            'exit_point': str,
            'observations': str,
            'created_by': str,
            'initial_images': List[str],
            'final_images': List[str]
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'reasons': 'reasons',
            'project': 'project',
            'id_truck_license': 'id_truck_license',
            'id_driver': 'id_driver',
            'initial_gasoline_id': 'initial_gasoline_id',
            'final_gasoline_id': 'final_gasoline_id',
            'initial_km': 'initial_km',
            'final_km': 'final_km',
            'driver_companion': 'driver_companion',
            'destiny': 'destiny',
            'exit_point': 'exit_point',
            'observations': 'observations',
            'created_by': 'created_by',
            'initial_images': 'initial_images',
            'final_images': 'final_images'
        }
        self._created_at = created_at
        self._reasons = reasons
        self._project = project
        self._id_truck_license = id_truck_license
        self._id_driver = id_driver
        self._initial_gasoline_id = initial_gasoline_id
        self._final_gasoline_id = final_gasoline_id
        self._initial_km = initial_km
        self._final_km = final_km
        self._driver_companion = driver_companion
        self._destiny = destiny
        self._exit_point = exit_point
        self._observations = observations
        self._created_by = created_by
        self._initial_images = initial_images
        self._final_images = final_images

    @classmethod
    def from_dict(cls, dikt) -> 'TechnicalData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TechnicalData of this TechnicalData.  # noqa: E501
        :rtype: TechnicalData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> str:
        """Gets the created_at of this TechnicalData.


        :return: The created_at of this TechnicalData.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this TechnicalData.


        :param created_at: The created_at of this TechnicalData.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def reasons(self) -> List[int]:
        """Gets the reasons of this TechnicalData.


        :return: The reasons of this TechnicalData.
        :rtype: List[int]
        """
        return self._reasons

    @reasons.setter
    def reasons(self, reasons: List[int]):
        """Sets the reasons of this TechnicalData.


        :param reasons: The reasons of this TechnicalData.
        :type reasons: List[int]
        """

        self._reasons = reasons

    @property
    def project(self) -> List[int]:
        """Gets the project of this TechnicalData.


        :return: The project of this TechnicalData.
        :rtype: List[int]
        """
        return self._project

    @project.setter
    def project(self, project: List[int]):
        """Sets the project of this TechnicalData.


        :param project: The project of this TechnicalData.
        :type project: List[int]
        """

        self._project = project

    @property
    def id_truck_license(self) -> int:
        """Gets the id_truck_license of this TechnicalData.


        :return: The id_truck_license of this TechnicalData.
        :rtype: int
        """
        return self._id_truck_license

    @id_truck_license.setter
    def id_truck_license(self, id_truck_license: int):
        """Sets the id_truck_license of this TechnicalData.


        :param id_truck_license: The id_truck_license of this TechnicalData.
        :type id_truck_license: int
        """

        self._id_truck_license = id_truck_license

    @property
    def id_driver(self) -> int:
        """Gets the id_driver of this TechnicalData.


        :return: The id_driver of this TechnicalData.
        :rtype: int
        """
        return self._id_driver

    @id_driver.setter
    def id_driver(self, id_driver: int):
        """Sets the id_driver of this TechnicalData.


        :param id_driver: The id_driver of this TechnicalData.
        :type id_driver: int
        """

        self._id_driver = id_driver

    @property
    def initial_gasoline_id(self) -> int:
        """Gets the initial_gasoline_id of this TechnicalData.


        :return: The initial_gasoline_id of this TechnicalData.
        :rtype: int
        """
        return self._initial_gasoline_id

    @initial_gasoline_id.setter
    def initial_gasoline_id(self, initial_gasoline_id: int):
        """Sets the initial_gasoline_id of this TechnicalData.


        :param initial_gasoline_id: The initial_gasoline_id of this TechnicalData.
        :type initial_gasoline_id: int
        """

        self._initial_gasoline_id = initial_gasoline_id

    @property
    def final_gasoline_id(self) -> int:
        """Gets the final_gasoline_id of this TechnicalData.


        :return: The final_gasoline_id of this TechnicalData.
        :rtype: int
        """
        return self._final_gasoline_id

    @final_gasoline_id.setter
    def final_gasoline_id(self, final_gasoline_id: int):
        """Sets the final_gasoline_id of this TechnicalData.


        :param final_gasoline_id: The final_gasoline_id of this TechnicalData.
        :type final_gasoline_id: int
        """

        self._final_gasoline_id = final_gasoline_id

    @property
    def initial_km(self) -> str:
        """Gets the initial_km of this TechnicalData.


        :return: The initial_km of this TechnicalData.
        :rtype: str
        """
        return self._initial_km

    @initial_km.setter
    def initial_km(self, initial_km: str):
        """Sets the initial_km of this TechnicalData.


        :param initial_km: The initial_km of this TechnicalData.
        :type initial_km: str
        """

        self._initial_km = initial_km

    @property
    def final_km(self) -> str:
        """Gets the final_km of this TechnicalData.


        :return: The final_km of this TechnicalData.
        :rtype: str
        """
        return self._final_km

    @final_km.setter
    def final_km(self, final_km: str):
        """Sets the final_km of this TechnicalData.


        :param final_km: The final_km of this TechnicalData.
        :type final_km: str
        """

        self._final_km = final_km

    @property
    def driver_companion(self) -> List[int]:
        """Gets the driver_companion of this TechnicalData.


        :return: The driver_companion of this TechnicalData.
        :rtype: List[int]
        """
        return self._driver_companion

    @driver_companion.setter
    def driver_companion(self, driver_companion: List[int]):
        """Sets the driver_companion of this TechnicalData.


        :param driver_companion: The driver_companion of this TechnicalData.
        :type driver_companion: List[int]
        """

        self._driver_companion = driver_companion

    @property
    def destiny(self) -> str:
        """Gets the destiny of this TechnicalData.


        :return: The destiny of this TechnicalData.
        :rtype: str
        """
        return self._destiny

    @destiny.setter
    def destiny(self, destiny: str):
        """Sets the destiny of this TechnicalData.


        :param destiny: The destiny of this TechnicalData.
        :type destiny: str
        """

        self._destiny = destiny

    @property
    def exit_point(self) -> str:
        """Gets the exit_point of this TechnicalData.


        :return: The exit_point of this TechnicalData.
        :rtype: str
        """
        return self._exit_point

    @exit_point.setter
    def exit_point(self, exit_point: str):
        """Sets the exit_point of this TechnicalData.


        :param exit_point: The exit_point of this TechnicalData.
        :type exit_point: str
        """

        self._exit_point = exit_point

    @property
    def observations(self) -> str:
        """Gets the observations of this TechnicalData.


        :return: The observations of this TechnicalData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this TechnicalData.


        :param observations: The observations of this TechnicalData.
        :type observations: str
        """

        self._observations = observations

    @property
    def created_by(self) -> str:
        """Gets the created_by of this TechnicalData.


        :return: The created_by of this TechnicalData.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by: str):
        """Sets the created_by of this TechnicalData.


        :param created_by: The created_by of this TechnicalData.
        :type created_by: str
        """

        self._created_by = created_by

    @property
    def initial_images(self) -> List[str]:
        """Gets the initial_images of this TechnicalData.


        :return: The initial_images of this TechnicalData.
        :rtype: List[str]
        """
        return self._initial_images

    @initial_images.setter
    def initial_images(self, initial_images: List[str]):
        """Sets the initial_images of this TechnicalData.


        :param initial_images: The initial_images of this TechnicalData.
        :type initial_images: List[str]
        """

        self._initial_images = initial_images

    @property
    def final_images(self) -> List[str]:
        """Gets the final_images of this TechnicalData.


        :return: The final_images of this TechnicalData.
        :rtype: List[str]
        """
        return self._final_images

    @final_images.setter
    def final_images(self, final_images: List[str]):
        """Sets the final_images of this TechnicalData.


        :param final_images: The final_images of this TechnicalData.
        :type final_images: List[str]
        """

        self._final_images = final_images
