# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.materials_data import MaterialsData  # noqa: F401,E501
from swagger_server import util


class TechnicalData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, materials: List[MaterialsData]=None, task_id: int=None, client_id: int=None, location_id: int=None, technical_staff: List[float]=None, resume: str=None, vehicle: str=None, user: str=None, images: List[str]=None):  # noqa: E501
        """TechnicalData - a model defined in Swagger

        :param materials: The materials of this TechnicalData.  # noqa: E501
        :type materials: List[MaterialsData]
        :param task_id: The task_id of this TechnicalData.  # noqa: E501
        :type task_id: int
        :param client_id: The client_id of this TechnicalData.  # noqa: E501
        :type client_id: int
        :param location_id: The location_id of this TechnicalData.  # noqa: E501
        :type location_id: int
        :param technical_staff: The technical_staff of this TechnicalData.  # noqa: E501
        :type technical_staff: List[float]
        :param resume: The resume of this TechnicalData.  # noqa: E501
        :type resume: str
        :param vehicle: The vehicle of this TechnicalData.  # noqa: E501
        :type vehicle: str
        :param user: The user of this TechnicalData.  # noqa: E501
        :type user: str
        :param images: The images of this TechnicalData.  # noqa: E501
        :type images: List[str]
        """
        self.swagger_types = {
            'materials': List[MaterialsData],
            'task_id': int,
            'client_id': int,
            'location_id': int,
            'technical_staff': List[float],
            'resume': str,
            'vehicle': str,
            'user': str,
            'images': List[str]
        }

        self.attribute_map = {
            'materials': 'materials',
            'task_id': 'task_id',
            'client_id': 'client_id',
            'location_id': 'location_id',
            'technical_staff': 'technical_staff',
            'resume': 'resume',
            'vehicle': 'vehicle',
            'user': 'user',
            'images': 'images'
        }
        self._materials = materials
        self._task_id = task_id
        self._client_id = client_id
        self._location_id = location_id
        self._technical_staff = technical_staff
        self._resume = resume
        self._vehicle = vehicle
        self._user = user
        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'TechnicalData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TechnicalData of this TechnicalData.  # noqa: E501
        :rtype: TechnicalData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def materials(self) -> List[MaterialsData]:
        """Gets the materials of this TechnicalData.


        :return: The materials of this TechnicalData.
        :rtype: List[MaterialsData]
        """
        return self._materials

    @materials.setter
    def materials(self, materials: List[MaterialsData]):
        """Sets the materials of this TechnicalData.


        :param materials: The materials of this TechnicalData.
        :type materials: List[MaterialsData]
        """

        self._materials = materials

    @property
    def task_id(self) -> int:
        """Gets the task_id of this TechnicalData.


        :return: The task_id of this TechnicalData.
        :rtype: int
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id: int):
        """Sets the task_id of this TechnicalData.


        :param task_id: The task_id of this TechnicalData.
        :type task_id: int
        """

        self._task_id = task_id

    @property
    def client_id(self) -> int:
        """Gets the client_id of this TechnicalData.


        :return: The client_id of this TechnicalData.
        :rtype: int
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: int):
        """Sets the client_id of this TechnicalData.


        :param client_id: The client_id of this TechnicalData.
        :type client_id: int
        """

        self._client_id = client_id

    @property
    def location_id(self) -> int:
        """Gets the location_id of this TechnicalData.


        :return: The location_id of this TechnicalData.
        :rtype: int
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id: int):
        """Sets the location_id of this TechnicalData.


        :param location_id: The location_id of this TechnicalData.
        :type location_id: int
        """

        self._location_id = location_id

    @property
    def technical_staff(self) -> List[float]:
        """Gets the technical_staff of this TechnicalData.


        :return: The technical_staff of this TechnicalData.
        :rtype: List[float]
        """
        return self._technical_staff

    @technical_staff.setter
    def technical_staff(self, technical_staff: List[float]):
        """Sets the technical_staff of this TechnicalData.


        :param technical_staff: The technical_staff of this TechnicalData.
        :type technical_staff: List[float]
        """

        self._technical_staff = technical_staff

    @property
    def resume(self) -> str:
        """Gets the resume of this TechnicalData.


        :return: The resume of this TechnicalData.
        :rtype: str
        """
        return self._resume

    @resume.setter
    def resume(self, resume: str):
        """Sets the resume of this TechnicalData.


        :param resume: The resume of this TechnicalData.
        :type resume: str
        """

        self._resume = resume

    @property
    def vehicle(self) -> str:
        """Gets the vehicle of this TechnicalData.


        :return: The vehicle of this TechnicalData.
        :rtype: str
        """
        return self._vehicle

    @vehicle.setter
    def vehicle(self, vehicle: str):
        """Sets the vehicle of this TechnicalData.


        :param vehicle: The vehicle of this TechnicalData.
        :type vehicle: str
        """

        self._vehicle = vehicle

    @property
    def user(self) -> str:
        """Gets the user of this TechnicalData.


        :return: The user of this TechnicalData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this TechnicalData.


        :param user: The user of this TechnicalData.
        :type user: str
        """

        self._user = user

    @property
    def images(self) -> List[str]:
        """Gets the images of this TechnicalData.


        :return: The images of this TechnicalData.
        :rtype: List[str]
        """
        return self._images

    @images.setter
    def images(self, images: List[str]):
        """Sets the images of this TechnicalData.


        :param images: The images of this TechnicalData.
        :type images: List[str]
        """

        self._images = images
