# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TechnicalPutData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_movilization: int=None, final_gasoline_id: int=None, final_km: str=None, have_incident: bool=None, detail_incident: str=None, exit_date: str=None, final_images: List[str]=None):  # noqa: E501
        """TechnicalPutData - a model defined in Swagger

        :param id_movilization: The id_movilization of this TechnicalPutData.  # noqa: E501
        :type id_movilization: int
        :param final_gasoline_id: The final_gasoline_id of this TechnicalPutData.  # noqa: E501
        :type final_gasoline_id: int
        :param final_km: The final_km of this TechnicalPutData.  # noqa: E501
        :type final_km: str
        :param have_incident: The have_incident of this TechnicalPutData.  # noqa: E501
        :type have_incident: bool
        :param detail_incident: The detail_incident of this TechnicalPutData.  # noqa: E501
        :type detail_incident: str
        :param exit_date: The exit_date of this TechnicalPutData.  # noqa: E501
        :type exit_date: str
        :param final_images: The final_images of this TechnicalPutData.  # noqa: E501
        :type final_images: List[str]
        """
        self.swagger_types = {
            'id_movilization': int,
            'final_gasoline_id': int,
            'final_km': str,
            'have_incident': bool,
            'detail_incident': str,
            'exit_date': str,
            'final_images': List[str]
        }

        self.attribute_map = {
            'id_movilization': 'id_movilization',
            'final_gasoline_id': 'final_gasoline_id',
            'final_km': 'final_km',
            'have_incident': 'have_incident',
            'detail_incident': 'detail_incident',
            'exit_date': 'exit_date',
            'final_images': 'final_images'
        }
        self._id_movilization = id_movilization
        self._final_gasoline_id = final_gasoline_id
        self._final_km = final_km
        self._have_incident = have_incident
        self._detail_incident = detail_incident
        self._exit_date = exit_date
        self._final_images = final_images

    @classmethod
    def from_dict(cls, dikt) -> 'TechnicalPutData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TechnicalPutData of this TechnicalPutData.  # noqa: E501
        :rtype: TechnicalPutData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_movilization(self) -> int:
        """Gets the id_movilization of this TechnicalPutData.


        :return: The id_movilization of this TechnicalPutData.
        :rtype: int
        """
        return self._id_movilization

    @id_movilization.setter
    def id_movilization(self, id_movilization: int):
        """Sets the id_movilization of this TechnicalPutData.


        :param id_movilization: The id_movilization of this TechnicalPutData.
        :type id_movilization: int
        """

        self._id_movilization = id_movilization

    @property
    def final_gasoline_id(self) -> int:
        """Gets the final_gasoline_id of this TechnicalPutData.


        :return: The final_gasoline_id of this TechnicalPutData.
        :rtype: int
        """
        return self._final_gasoline_id

    @final_gasoline_id.setter
    def final_gasoline_id(self, final_gasoline_id: int):
        """Sets the final_gasoline_id of this TechnicalPutData.


        :param final_gasoline_id: The final_gasoline_id of this TechnicalPutData.
        :type final_gasoline_id: int
        """

        self._final_gasoline_id = final_gasoline_id

    @property
    def final_km(self) -> str:
        """Gets the final_km of this TechnicalPutData.


        :return: The final_km of this TechnicalPutData.
        :rtype: str
        """
        return self._final_km

    @final_km.setter
    def final_km(self, final_km: str):
        """Sets the final_km of this TechnicalPutData.


        :param final_km: The final_km of this TechnicalPutData.
        :type final_km: str
        """

        self._final_km = final_km

    @property
    def have_incident(self) -> bool:
        """Gets the have_incident of this TechnicalPutData.


        :return: The have_incident of this TechnicalPutData.
        :rtype: bool
        """
        return self._have_incident

    @have_incident.setter
    def have_incident(self, have_incident: bool):
        """Sets the have_incident of this TechnicalPutData.


        :param have_incident: The have_incident of this TechnicalPutData.
        :type have_incident: bool
        """

        self._have_incident = have_incident

    @property
    def detail_incident(self) -> str:
        """Gets the detail_incident of this TechnicalPutData.


        :return: The detail_incident of this TechnicalPutData.
        :rtype: str
        """
        return self._detail_incident

    @detail_incident.setter
    def detail_incident(self, detail_incident: str):
        """Sets the detail_incident of this TechnicalPutData.


        :param detail_incident: The detail_incident of this TechnicalPutData.
        :type detail_incident: str
        """

        self._detail_incident = detail_incident

    @property
    def exit_date(self) -> str:
        """Gets the exit_date of this TechnicalPutData.


        :return: The exit_date of this TechnicalPutData.
        :rtype: str
        """
        return self._exit_date

    @exit_date.setter
    def exit_date(self, exit_date: str):
        """Sets the exit_date of this TechnicalPutData.


        :param exit_date: The exit_date of this TechnicalPutData.
        :type exit_date: str
        """

        self._exit_date = exit_date

    @property
    def final_images(self) -> List[str]:
        """Gets the final_images of this TechnicalPutData.


        :return: The final_images of this TechnicalPutData.
        :rtype: List[str]
        """
        return self._final_images

    @final_images.setter
    def final_images(self, final_images: List[str]):
        """Sets the final_images of this TechnicalPutData.


        :param final_images: The final_images of this TechnicalPutData.
        :type final_images: List[str]
        """

        self._final_images = final_images
