# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.driver_companion import DriverCompanion  # noqa: F401,E501
from swagger_server.models.project import Project  # noqa: F401,E501
from swagger_server.models.reasons import Reasons  # noqa: F401,E501
from swagger_server import util


class TehnicalData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, created_at: str=None, reasons: Reasons=None, project: Project=None, id_truck_license: int=None, id_level_gasoline: int=None, initial_km: str=None, driver_companion: DriverCompanion=None, starting_point: str=None, route_point: str=None, obseervations: str=None, images: List[str]=None):  # noqa: E501
        """TehnicalData - a model defined in Swagger

        :param created_at: The created_at of this TehnicalData.  # noqa: E501
        :type created_at: str
        :param reasons: The reasons of this TehnicalData.  # noqa: E501
        :type reasons: Reasons
        :param project: The project of this TehnicalData.  # noqa: E501
        :type project: Project
        :param id_truck_license: The id_truck_license of this TehnicalData.  # noqa: E501
        :type id_truck_license: int
        :param id_level_gasoline: The id_level_gasoline of this TehnicalData.  # noqa: E501
        :type id_level_gasoline: int
        :param initial_km: The initial_km of this TehnicalData.  # noqa: E501
        :type initial_km: str
        :param driver_companion: The driver_companion of this TehnicalData.  # noqa: E501
        :type driver_companion: DriverCompanion
        :param starting_point: The starting_point of this TehnicalData.  # noqa: E501
        :type starting_point: str
        :param route_point: The route_point of this TehnicalData.  # noqa: E501
        :type route_point: str
        :param obseervations: The obseervations of this TehnicalData.  # noqa: E501
        :type obseervations: str
        :param images: The images of this TehnicalData.  # noqa: E501
        :type images: List[str]
        """
        self.swagger_types = {
            'created_at': str,
            'reasons': Reasons,
            'project': Project,
            'id_truck_license': int,
            'id_level_gasoline': int,
            'initial_km': str,
            'driver_companion': DriverCompanion,
            'starting_point': str,
            'route_point': str,
            'obseervations': str,
            'images': List[str]
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'reasons': 'reasons',
            'project': 'project',
            'id_truck_license': 'id_truck_license',
            'id_level_gasoline': 'id_level_gasoline',
            'initial_km': 'initial_km',
            'driver_companion': 'driver_companion',
            'starting_point': 'starting_point',
            'route_point': 'route_point',
            'obseervations': 'obseervations',
            'images': 'images'
        }
        self._created_at = created_at
        self._reasons = reasons
        self._project = project
        self._id_truck_license = id_truck_license
        self._id_level_gasoline = id_level_gasoline
        self._initial_km = initial_km
        self._driver_companion = driver_companion
        self._starting_point = starting_point
        self._route_point = route_point
        self._obseervations = obseervations
        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'TehnicalData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TehnicalData of this TehnicalData.  # noqa: E501
        :rtype: TehnicalData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> str:
        """Gets the created_at of this TehnicalData.


        :return: The created_at of this TehnicalData.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this TehnicalData.


        :param created_at: The created_at of this TehnicalData.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def reasons(self) -> Reasons:
        """Gets the reasons of this TehnicalData.


        :return: The reasons of this TehnicalData.
        :rtype: Reasons
        """
        return self._reasons

    @reasons.setter
    def reasons(self, reasons: Reasons):
        """Sets the reasons of this TehnicalData.


        :param reasons: The reasons of this TehnicalData.
        :type reasons: Reasons
        """

        self._reasons = reasons

    @property
    def project(self) -> Project:
        """Gets the project of this TehnicalData.


        :return: The project of this TehnicalData.
        :rtype: Project
        """
        return self._project

    @project.setter
    def project(self, project: Project):
        """Sets the project of this TehnicalData.


        :param project: The project of this TehnicalData.
        :type project: Project
        """

        self._project = project

    @property
    def id_truck_license(self) -> int:
        """Gets the id_truck_license of this TehnicalData.


        :return: The id_truck_license of this TehnicalData.
        :rtype: int
        """
        return self._id_truck_license

    @id_truck_license.setter
    def id_truck_license(self, id_truck_license: int):
        """Sets the id_truck_license of this TehnicalData.


        :param id_truck_license: The id_truck_license of this TehnicalData.
        :type id_truck_license: int
        """

        self._id_truck_license = id_truck_license

    @property
    def id_level_gasoline(self) -> int:
        """Gets the id_level_gasoline of this TehnicalData.


        :return: The id_level_gasoline of this TehnicalData.
        :rtype: int
        """
        return self._id_level_gasoline

    @id_level_gasoline.setter
    def id_level_gasoline(self, id_level_gasoline: int):
        """Sets the id_level_gasoline of this TehnicalData.


        :param id_level_gasoline: The id_level_gasoline of this TehnicalData.
        :type id_level_gasoline: int
        """

        self._id_level_gasoline = id_level_gasoline

    @property
    def initial_km(self) -> str:
        """Gets the initial_km of this TehnicalData.


        :return: The initial_km of this TehnicalData.
        :rtype: str
        """
        return self._initial_km

    @initial_km.setter
    def initial_km(self, initial_km: str):
        """Sets the initial_km of this TehnicalData.


        :param initial_km: The initial_km of this TehnicalData.
        :type initial_km: str
        """

        self._initial_km = initial_km

    @property
    def driver_companion(self) -> DriverCompanion:
        """Gets the driver_companion of this TehnicalData.


        :return: The driver_companion of this TehnicalData.
        :rtype: DriverCompanion
        """
        return self._driver_companion

    @driver_companion.setter
    def driver_companion(self, driver_companion: DriverCompanion):
        """Sets the driver_companion of this TehnicalData.


        :param driver_companion: The driver_companion of this TehnicalData.
        :type driver_companion: DriverCompanion
        """

        self._driver_companion = driver_companion

    @property
    def starting_point(self) -> str:
        """Gets the starting_point of this TehnicalData.


        :return: The starting_point of this TehnicalData.
        :rtype: str
        """
        return self._starting_point

    @starting_point.setter
    def starting_point(self, starting_point: str):
        """Sets the starting_point of this TehnicalData.


        :param starting_point: The starting_point of this TehnicalData.
        :type starting_point: str
        """

        self._starting_point = starting_point

    @property
    def route_point(self) -> str:
        """Gets the route_point of this TehnicalData.


        :return: The route_point of this TehnicalData.
        :rtype: str
        """
        return self._route_point

    @route_point.setter
    def route_point(self, route_point: str):
        """Sets the route_point of this TehnicalData.


        :param route_point: The route_point of this TehnicalData.
        :type route_point: str
        """

        self._route_point = route_point

    @property
    def obseervations(self) -> str:
        """Gets the obseervations of this TehnicalData.


        :return: The obseervations of this TehnicalData.
        :rtype: str
        """
        return self._obseervations

    @obseervations.setter
    def obseervations(self, obseervations: str):
        """Sets the obseervations of this TehnicalData.


        :param obseervations: The obseervations of this TehnicalData.
        :type obseervations: str
        """

        self._obseervations = obseervations

    @property
    def images(self) -> List[str]:
        """Gets the images of this TehnicalData.


        :return: The images of this TehnicalData.
        :rtype: List[str]
        """
        return self._images

    @images.setter
    def images(self, images: List[str]):
        """Sets the images of this TehnicalData.


        :param images: The images of this TehnicalData.
        :type images: List[str]
        """

        self._images = images
